# Generated by Django 4.2.16 on 2024-10-09 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date rented')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date checkout')),
                ('rental_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('wait', 'Wait')], default='wait', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=200)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('wait', 'Wait')], default='wait', max_length=10)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renthub.rental')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renthub.renter'),
        ),
        migrations.AddField(
            model_name='rental',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renthub.room'),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField()),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('wait', 'Wait')], default='wait', max_length=10)),
                ('date_requested', models.DateTimeField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renthub.rental')),
            ],
        ),
    ]
