# Generated by Django 5.1 on 2024-10-27 14:33

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("renthub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyOwner",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Property Owner",
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 26, 14, 33, 29, 910148, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date checkout",
            ),
        ),
    ]
