# Generated by Django 5.1.2 on 2024-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="availability",
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
