# Generated by Django 4.2.16 on 2024-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('wait', 'Wait')], default='Wait', max_length=10),
        ),
    ]
