# Generated by Django 5.1.2 on 2024-10-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0002_rentalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='renthub.renter')),
            ],
        ),
    ]
