# Generated by Django 5.1 on 2024-10-28 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0002_propertyowner_maintenancerequest_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 27, 6, 41, 29, 102519, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date checkout",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="ideal_for",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
