# Generated by Django 5.1 on 2024-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0002_rentalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='status',
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('wait', 'Wait')], default='wait', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slip_images/'),
        ),
    ]
