# Generated by Django 5.1.1 on 2024-10-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0002_roomtype_rename_start_data_rental_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='ideal_for',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
