# Generated by Django 5.1 on 2024-10-26 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0002_remove_room_availability_maintenancerequest_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 25, 7, 19, 17, 764995, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date checkout",
            ),
        ),
    ]
