# Generated by Django 5.1.2 on 2024-10-31 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0003_alter_rental_end_date_alter_roomtype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 14, 14, 39, 70991, tzinfo=datetime.timezone.utc), verbose_name='date checkout'),
        ),
    ]
