# Generated by Django 5.1.1 on 2024-10-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0003_roomtype_description_roomtype_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='features',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='renthub.roomtype')),
            ],
        ),
    ]
