# Generated by Django 4.2.16 on 2024-10-24 02:12

from django.db import migrations, models
import renthub.utils


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0004_alter_maintenancerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('wait', 'wait')], default=renthub.utils.Status['wait'], max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('wait', 'wait')], default=renthub.utils.Status['wait'], max_length=10),
        ),
    ]
