# Generated by Django 5.1.2 on 2024-11-06 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0005_alter_notification_options_alter_rental_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 12, 32, 27, 97451, tzinfo=datetime.timezone.utc), verbose_name='date checkout'),
        ),
    ]
