# Generated by Django 5.1.2 on 2024-11-07 16:20

import datetime
import django.db.models.deletion
import renthub.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0006_alter_announcement_content_alter_rental_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='last_checked_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 16, 20, 5, 386970, tzinfo=datetime.timezone.utc), verbose_name='date checkout'),
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slip_images/')),
                ('status', models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('wait', 'wait')], default=renthub.utils.Status['wait'], max_length=10)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renthub.renter')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renthub.room')),
            ],
        ),
    ]
