# Generated by Django 5.1.2 on 2024-11-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0008_alter_rental_end_date_alter_roomtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='electric_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='water_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date checkout'),
        ),
    ]
