# Generated by Django 5.1.2 on 2024-11-13 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0009_rental_electric_fee_rental_water_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date checkout'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date rented'),
        ),
    ]
