# Generated by Django 5.1.2 on 2024-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0010_alter_rental_end_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_floor',
            field=models.IntegerField(default=0),
        ),
    ]
