# Generated by Django 5.1.2 on 2024-11-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0011_room_room_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="renter",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AddField(
            model_name="renter",
            name="thai_citizenship_id",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
