# Generated by Django 5.1.2 on 2024-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0012_alter_notification_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
