# Generated by Django 5.1.2 on 2024-11-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0013_alter_renter_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renter",
            name="profile_picture",
        ),
    ]
