# Generated by Django 5.1.2 on 2024-11-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0013_rental_last_paid_date"),
        ("renthub", "0014_remove_renter_profile_picture"),
    ]

    operations = []
