# Generated by Django 5.1.2 on 2024-11-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0020_renter_thai_citizenship_id_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='thai_citizenship_id_card',
            new_name='thai_citizenship_id_image',
        ),
    ]
