# Generated by Django 5.1.2 on 2024-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renthub', '0022_alter_renter_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='is_valid',
            field=models.BooleanField(default=False, help_text="Is the renter's thai_citizenship_id_image valid?"),
        ),
    ]
